package com.lch.base.basedb.model;

import java.util.Date;

public class TLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.operatorDate
     *
     * @mbggenerated
     */
    private Date operatordate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.descript
     *
     * @mbggenerated
     */
    private String descript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.id
     *
     * @return the value of t_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.id
     *
     * @param id the value for t_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.operator
     *
     * @return the value of t_log.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.operator
     *
     * @param operator the value for t_log.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.operatorDate
     *
     * @return the value of t_log.operatorDate
     *
     * @mbggenerated
     */
    public Date getOperatordate() {
        return operatordate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.operatorDate
     *
     * @param operatordate the value for t_log.operatorDate
     *
     * @mbggenerated
     */
    public void setOperatordate(Date operatordate) {
        this.operatordate = operatordate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.descript
     *
     * @return the value of t_log.descript
     *
     * @mbggenerated
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.descript
     *
     * @param descript the value for t_log.descript
     *
     * @mbggenerated
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }
}