package com.lch.base.basedb.model;

public class TRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_enname
     *
     * @mbggenerated
     */
    private String roleEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_remark
     *
     * @mbggenerated
     */
    private String roleRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_id
     *
     * @return the value of t_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_id
     *
     * @param roleId the value for t_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_name
     *
     * @return the value of t_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_name
     *
     * @param roleName the value for t_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_enname
     *
     * @return the value of t_role.role_enname
     *
     * @mbggenerated
     */
    public String getRoleEnname() {
        return roleEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_enname
     *
     * @param roleEnname the value for t_role.role_enname
     *
     * @mbggenerated
     */
    public void setRoleEnname(String roleEnname) {
        this.roleEnname = roleEnname == null ? null : roleEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_remark
     *
     * @return the value of t_role.role_remark
     *
     * @mbggenerated
     */
    public String getRoleRemark() {
        return roleRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_remark
     *
     * @param roleRemark the value for t_role.role_remark
     *
     * @mbggenerated
     */
    public void setRoleRemark(String roleRemark) {
        this.roleRemark = roleRemark == null ? null : roleRemark.trim();
    }
}