package com.lch.base.basedb.data;

import com.lch.base.basedb.model.QrtzTriggers;
import com.lch.base.basedb.model.QrtzTriggersExample;
import com.lch.base.basedb.model.QrtzTriggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int countByExample(QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int deleteByExample(QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(QrtzTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int insert(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int insertSelective(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    List<QrtzTriggers> selectByExampleWithBLOBs(QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    List<QrtzTriggers> selectByExample(QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    QrtzTriggers selectByPrimaryKey(QrtzTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QrtzTriggers record, @Param("example") QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzTriggers record, @Param("example") QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QrtzTriggers record, @Param("example") QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QrtzTriggers record);
}