package com.lch.base.basedb.data;

import com.lch.base.basedb.model.QrtzSimpropTriggers;
import com.lch.base.basedb.model.QrtzSimpropTriggersExample;
import com.lch.base.basedb.model.QrtzSimpropTriggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzSimpropTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int countByExample(QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int deleteByExample(QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(QrtzSimpropTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int insert(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int insertSelective(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    List<QrtzSimpropTriggers> selectByExample(QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    QrtzSimpropTriggers selectByPrimaryKey(QrtzSimpropTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QrtzSimpropTriggers record, @Param("example") QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QrtzSimpropTriggers record, @Param("example") QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QrtzSimpropTriggers record);
}