package com.lch.base.basedb.data;

import com.lch.base.basedb.model.QrtzSchedulerState;
import com.lch.base.basedb.model.QrtzSchedulerStateExample;
import com.lch.base.basedb.model.QrtzSchedulerStateKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzSchedulerStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int countByExample(QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int deleteByExample(QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(QrtzSchedulerStateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int insert(QrtzSchedulerState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int insertSelective(QrtzSchedulerState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    List<QrtzSchedulerState> selectByExample(QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    QrtzSchedulerState selectByPrimaryKey(QrtzSchedulerStateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QrtzSchedulerState record, @Param("example") QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QrtzSchedulerState record, @Param("example") QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QrtzSchedulerState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QrtzSchedulerState record);
}