package com.lch.base.basedb.data;

import com.lch.base.basedb.model.QrtzCalendars;
import com.lch.base.basedb.model.QrtzCalendarsExample;
import com.lch.base.basedb.model.QrtzCalendarsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzCalendarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int countByExample(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int deleteByExample(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(QrtzCalendarsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int insert(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int insertSelective(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    List<QrtzCalendars> selectByExampleWithBLOBs(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    List<QrtzCalendars> selectByExample(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    QrtzCalendars selectByPrimaryKey(QrtzCalendarsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QrtzCalendars record, @Param("example") QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzCalendars record, @Param("example") QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QrtzCalendars record, @Param("example") QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(QrtzCalendars record);
}