package com.lch.base.basedb.data;

import com.lch.base.basedb.model.TLog;
import com.lch.base.basedb.model.TLogExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    int countByExample(TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    int deleteByExample(TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    int insert(TLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    int insertSelective(TLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    List<TLog> selectByExample(TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    TLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TLog record, @Param("example") TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TLog record, @Param("example") TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TLog record);
    
    List<TLog> getTLogList(Map<String,Object> map);
    
    int getTLogCount(Map<String,Object> map);
}